apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 15m
  path: ./kafka/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system